// PortfolioItem — محفظة أعمال المقاول (مشاريع سابقة / صور قبل وبعد)
const mongoose = require('mongoose');

const imageSchema = new mongoose.Schema(
  {
    filename: { type: String, required: true },
    originalName: { type: String, required: true },
    mimetype: { type: String, required: true },
    size: { type: Number, required: true },
    uploadedAt: { type: Date, default: Date.now },
  },
  { _id: false }
);

const portfolioItemSchema = new mongoose.Schema(
  {
    contractor: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
      index: true,
    },
    title: { type: String, required: true, trim: true, maxlength: 120 },
    description: { type: String, maxlength: 500, default: '' },
    projectType: {
      type: String,
      enum: [
        'new_construction', 'finishing', 'renovation', 'repair',
        'extension', 'demolition', 'electrical', 'plumbing', 'other',
      ],
      default: 'other',
    },
    images: { type: [imageSchema], default: [] },
    beforePhotos: { type: [imageSchema], default: [] },
    afterPhotos: { type: [imageSchema], default: [] },
    completedAt: { type: Date, default: Date.now },
    governorate: { type: String, default: '' },
    durationMonths: { type: Number, min: 0, default: null },
    // لو جاي من إغلاق مشروع حقيقي على المنصة
    sourceProject: { type: mongoose.Schema.Types.ObjectId, ref: 'Project', default: null },
    isAutoGenerated: { type: Boolean, default: false },
  },
  { timestamps: true }
);

portfolioItemSchema.index({ contractor: 1, createdAt: -1 });

module.exports = mongoose.model('PortfolioItem', portfolioItemSchema);
